CREATE TABLE HOTEL
(
  HOTEL_ID NUMBER NOT NULL,
  RENAVATION_DATE DATE NOT NULL,
  HOTEL_ADDRESS VARCHAR2(200) NOT NULL
);

ALTER TABLE HOTEL ADD CONSTRAINT HOTEL_PK PRIMARY KEY (HOTEL_ID);

INSERT INTO HOTEL VALUES (1, '22-07-19', 'Институтск');
INSERT INTO HOTEL VALUES (2, '23-07-19', 'Крещатик');
INSERT INTO HOTEL VALUES (3, '24-07-19', 'Петропавло');
INSERT INTO HOTEL VALUES (4, '25-07-19', 'Yaroslavov');
INSERT INTO HOTEL VALUES (5, '26-07-19', 'Kiltseva');